name: Build and Publish .NET Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Lab14-PaulDelgado.sln

      - name: Build application
        run: dotnet build Lab14-PaulDelgado.sln --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish Api/Api.csproj --configuration Release --output ./published
